### ISSUE TITLE
Checklist de Temas Cubiertos

### ISSUE THREAD

**Issue by ELC** [ELC/TUPPython#15]
Este issue hace una comparación de los temas dados en https://github.com/ELC/python-tutorial/tree/es y los comparas con los cubiertos por esta práctica.

En el #14 ya se abarcan los capítulos 1 y 2 así que este ticket está enfocado a los capitulos restantes.

- [ ] Capitulo 3: Control de Flujo
  - [x] Bloque IF -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_01.py
  - [x] Bloque IF-ELSE -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_03.py
  - [ ] Bloque IF-ELIF-ELSE
  - [ ] Bucle FOR + range
  - [x] Bucle FOR + lista -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_05.py 
  - [x] Bucle FOR + enumerate -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_12.py
  - [x] Bucle FOR + zip -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_12.py 
  - [ ] Bucle FOR + enumerate + zip
  - [ ] Bucle FOR + diccionarios
  - [x] Bucle FOR + break -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_10.py
  - [x] Bucle FOR-ELSE -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_10.py
  - [ ] Bucle FOR + continue
  - [ ] Bucle WHILE
  - [ ] Bucle DO-WHILE
  - [ ] Bloque TRY-EXCEPT
  - [ ] Bloque TRY-EXCEPT-FINALLY

- [ ] Capìtulo 4: Funciones
  - [ ] Funcion y parámetros
  - [ ] Función sin return
  - [ ] Type-Hints
  - [ ] Formas de invocación de funciones
  - [ ] Valores por defecto
  - [x] Mùltiples Return -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_03.py
  - [x] Return Expression -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_04.py
  - [ ] Return con múltiples valores
  - [x] Parámetros arbitrarios posicionales (*args) -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_02.py
  - [ ] Parámetros arbitrarios por palabra clave (*kwargs)
  - [ ] Funciones de Orden Superior
  - [x] Clousures -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_13.py
  - [x] Evaluación Parcial -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_14.py
  - [ ] Funciones anónimas (Lambdas)
  - [x] Funciones sobre funciones (map, filter y reduce) -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_11.py
  - [x] Comprensiones de Listas -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_11.py

- [ ] Capítulo 5: Paradigma Orientado a Objetos
  - [x] Constructor, Métodos y Variables de instancia -> https://github.com/ELC/TUPPython/blob/master/practico_03/ejercicio_01.py
  - [x] Variables y Métodos de clase -> https://github.com/ELC/TUPPython/blob/master/practico_03/ejercicio_02.py
  - [x] Dataclasses -> https://github.com/ELC/TUPPython/blob/master/practico_03/ejercicio_03.py
  - [x] Sobrecarga de Operadores -> https://github.com/ELC/TUPPython/blob/master/practico_03/ejercicio_07.py
  - [ ] Propiedades
  - [x] Copia Profunda -> https://github.com/ELC/TUPPython/blob/master/practico_03/ejercicio_08.py
  - [x] Herencia
  - [ ] Clases y Métodos abstractos
  - [ ] Sobrecarga de Métodos

- [ ] Capítulo 6: Módulos
  - [x] Importar de la biblioteca estándar
  - [x] Imports absolutos
  - [ ] Imports relativos
  - [ ] Comportamiento de Singleton de un módulo
  - [ ] \_\_init__.py
  - [ ] \_\_main__.py

- [ ] Capítulo 7: Funciones Avanzadas
  - [ ] Namedtuple
  - [ ] Counter
  - [ ] Defaultdict
  - [ ] Enum
  - [x] Generadores -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_13.py
  - [ ] Iteradores
  - [ ] Semicorrutinas
  - [ ] Corrutinas (asynio)
  - [x] Decoradores -> https://github.com/ELC/TUPPython/blob/master/practico_01/ejercicio_15.py
  - [ ] Context Manager
  - [ ] Itertools
  - [ ] OS
  - [ ] Pickle
  - [ ] JSON
  - [ ] Emails

**Comment by ELC** [comment]
Posibles Cambios:

- Re-organizar **TODOS** los TPs para que el orden de los ejercicios sea lo más parecido al del curso
- Re-organizar el TP1 para que cubra **TODOS** los temas de los capítulos 3 y 4
- Completar el TP3 para que incluya **TODOS** los temas del capítulo 5 **EXCEPTO**  Sobrecarga de Métodos porque no es similar a como se hace en otros lenguajes
- Completar el TP2 para que incluya \_\_init\_\_.py y \_\_main\_\_.py y el comportamiento como singleton
- Desarrollar un nuevo TP con los temas relevantes del capítulo 7:
  - Colecciones (NamedTuple, defaultdict, Counter y Enum)
  - Context Managers sencillos (sin clases)
  - Pickle y JSON
  - Itertools (básico)
  - OS (básico)
  - Decoradores (adaptar el ejercicio 15)

@pablobots Qué te parece esta organización? Hay algún tema que sacarías o que crees que haga falta?
